#!/bin/sh  
#  
#chkconfig: 2345 80 90  
#description: mongodb  
start() {
 /opt/mongodb/bin/mongod -f /opt/mongodb/bin/mongodb.conf
}

stop() {
 /opt/mongodb/bin/mongod -f /opt/mongodb/bin/mongodb.conf --shutdown
}

case "$1" in
  start)
 start
 ;;
  stop)
 stop
 ;;
  restart)
 stop
 start
 ;;
  *)
 echo $"Usage: $0 {start|stop|restart}"  
 exit 1
esac
